filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/nginx_logs/access.log
      - /usr/share/filebeat/nginx_logs/error.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644
